export const ProjectRest = {
    save: 'tom/project/save',
    getByUserId: 'tom/project/get',
    getProjectByProjectId: 'tom/project/getByProjectId',
    projectSchedule: 'tom/project/schedule',
    getScheduledOfFirm: 'tom/project/schedule/get',
    scheduleSendByPro: 'tom/project/schedule/send',
    getScheduledOfPro: 'tom/project/schedule/getScheduleOfPro',
    projectMeetDoneByAdmin: 'tom/project/schedule/complete',
    projectDeclineByPro: 'tom/project/schedule/decline',
    additionalReqDeclineByFirm: 'tom/project/firm/additional/decline',
    projectDeclineByFirm: 'tom/project/firm/decline',
    prjDeclineByProAfterMeeting: 'tom/project/pro/declineAfterMeeting',
    prjDeclineByFirmAfterMeeting: 'tom/project/firm/declineAfterMeeting',
    projectFinalize: 'tom/project/finalize',
    saveProjectAdditionTime: 'tom/project/additionaltime',
    projectFinalizeByFirm: 'tom/project/firm/finalize',
    addtionalReqFinalize: 'tom/project/firm/additional/finalize',
    projectFinalizeByAdmin: 'tom/project/admin/accept',
    additionalReqAcceptedByFirm: 'tom/project/admin/additional/accept',

    getDashboardProject: 'tom/project/dashboard',
    getLast2ProjectOfFirm: 'tom/project/last2project',
    saveAmends: 'tom/project/amends/save',
    saveAmendOfAddReq: 'tom/project/amends/additional/save',
}
